<header>
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <a href="/" class="logo" title="Dyreklinikken">
                            <img src="//<?= $_SERVER['HTTP_HOST'] ?>/assets/img/logo.png" alt="Logo" class="logo" height="55px"> <span class="sitename">Dyreklinikken</span>
                        </a>
                    </div>
                    <div class="col-md-9">
                        <nav>
                            <div class="clearfix">
                                <ul>
                                    <li class="nav">
                                        <a href="/" title="Forside">Forside</a>
                                    </li>
                                    <li class="nav">
                                        <a href="/priser" title="Priser">Priser</a>
                                    </li>
                                    <li class="nav">
                                        <a href="#" onclick="alert('Dette er et eksternt link, der ikke er tilgængeligt.');" title="Booking">Booking</a>
                                    </li>
                                    <li class="nav">
                                        <a href="#" onclick="alert('Dette er et eksternt link, der ikke er tilgængeligt.');" title="Shop">Shop</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
