<footer class="footer mt-5">
    <div class="container text-center text-md-left">
        <div class="row">
            <div class="col-md-9 pt-3">
                <div class="row">
                    <div class="col-md-3 mx-auto">
                        <img class="mt-3" height="50" src="https://i.imgur.com/Odwm52p.png">
                    </div>
                    <hr class="clearfix w-100 d-md-none">
                    <div class="col-md-3 mx-auto">
                        <h5 class="mt-3 mb-4">Dyreklinikken A/S</h5>
                        <ul class="list-unstyled">
                            <li>
                                Hospitalsgade 26
                            </li>
                            <li>
                                2400 København V,
                            </li>
                            <li>
                                Danmark
                            </li>
                            <li>
                                <br>
                            </li>
                            <li>
                                CVR: 40042199
                            </li>
                            <br />
                            <li>
                                <b>M: </b><a href="mailto:info@dyreklinikken.dk">info@dyreklinikken.dk</a></a>
                            </li>
                            <li>
                                <b>T: </b><a href="tel:+4570107070">+45 70 10 70 10</a>
                            </li>
                        </ul>
                    </div>
                    <hr class="clearfix w-100 d-md-none">
                    <div class="col-md-3 mx-auto">
                        <h5 class="mt-3 mb-4">Navigation</h5>
                        <ul class="links">
                            <li>
                                <a href="#!">Forside</a>
                            </li>
                            <li>
                                <a href="#!">Om os</a>
                            </li>
                            <li>
                                <a href="#!">Priser</a>
                            </li>
                            <li>
                                <a href="#!">Booking</a>
                            </li>
                            <li>
                                <a href="#!">Online Shop</a>
                            </li>
                            <li>
                                <a href="#!">Sitemap</a>
                            </li>
                        </ul>
                    </div>
                    <hr class="clearfix w-100 d-md-none">
                    <div class="col-md-3 mx-auto">
                        <h5 class="overskrift font-weight-bold mt-3 mb-4">Find din dyreklinik</h5>
                        <img height="200" src="https://i.imgur.com/qZtEgJH.png">
                    </div>
                    <div class="col mt-3">
                        <div class="left footer-copyright">&copy; 2019 Dyreklinikken A/S - Alle rettigheder forbeholdt</div>
                        <div class="right footer-copyright mt-2 mt-sm-0 mb-2"><a href="#!">Servicevilkår</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="#!">Privatlivspolitik</a> </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="emergency">
                    <h2>Akut?</h2>
                    <span class="emergency-text">
                        Ring til vores hotline:
                        <p class="emergency-phone">
                            +45 71 71 71 71
                        </p>
                    </span>
                </div>
            </div>
        </div>

    </div>

</footer>