<header>
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <a href="/" class="logo" title="Dyreklinikken">
                            <img src="//<?= $_SERVER['HTTP_HOST'] ?>/assets/img/logo.png" alt="Logo" class="logo" height="55px"> <span class="sitename">Dyreklinikken</span>
                        </a>
                    </div>
                    <div class="col-md-9">
                        <nav>
                            <div class="clearfix">
                                <ul>
                                    <li class="nav">
                                        <a href="/" title="Forside">Forside</a>
                                    </li>
                                    <li class="nav">
                                        <a href="/priser" title="Priser">Priser</a>
                                    </li>
                                    <li class="nav">
                                        <a href="#" onclick="alert('Dette er et eksternt link, der ikke er tilgængeligt.');" title="Booking">Booking</a>
                                    </li>
                                    <li class="nav">
                                        <a href="#" onclick="alert('Dette er et eksternt link, der ikke er tilgængeligt.');" title="Shop">Shop</a>
                                    </li>
                                    <li class="nav">
                                        <a href="/min-side" title="Min side">
                                        <span>
                                            <?php if(isset($_SESSION['SignedIn'])): ?>
                                                <?= $_SESSION['name'] ?>
                                            <?php else: ?>
                                                <em>Log ind</em>
                                            <?php endif ?>
                                        </span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
