<?php if(!isset($exe)) die("<b>Error!</b> This page should run through the router."); ?>
<!DOCTYPE html>
<html lang="da">
<?php tpl('head', 'Priser'); ?>
<body>
    <?php tpl('header'); ?>
    <section class="hero">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h1>
                            Vores priser
                        </h1>
                    </div>
                    <div class="col-md-4">
                        <aside class="">
                            
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <article>
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 content">

                        <div class="mb-6-5">
                            <h2>
                                Priser
                            </h2>
                            <p>
                                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia exercitationem dolorum fugiat, reprehenderit voluptate beatae ipsa a quam est, perferendis voluptas quos saepe eveniet temporibus sapiente dicta et ab! Adipisci architecto sit repellat quis autem eveniet commodi hic reprehenderit iste rem ullam veniam exercitationem voluptatum temporibus, suscipit quod quaerat! Neque, libero eos, debitis nobis aliquid iure repudiandae ratione aspernatur, omnis dolorum alias obcaecati non quibusdam blanditiis. Maxime ad iusto distinctio laboriosam eius, tenetur architecto neque, cupiditate accusamus doloribus voluptates officiis repellat debitis atque exercitationem totam. Porro laboriosam fuga quibusdam perferendis nobis quaerat incidunt, illo nihil velit nam suscipit magni voluptates?
                            </p>
                            </div>

                    </div>
                    <div class="col-md-3 sidebar">
                        <?php tpl('sidebar'); ?>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <?php tpl('footer'); ?>

    <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/da_dk/sdk.js#xfbml=1&version=v3.2&appId=251730689074894&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>