<?php if(!isset($exe)) die("<b>Error!</b> This page should run through the router."); ?>
<!DOCTYPE html>
<html lang="da">
<?php tpl('head', 'Priser'); ?>
<body>
    <?php tpl('header'); ?>
    <section class="hero mb-5">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">
                        <h1>
                            Vores priser
                        </h1>
                    </div>
                    <div class="col-md-4">
                        <aside class="">
                            
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <article>
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 content">

                        <div class="mb-6-5">
                            <h2>
                                Almindelige ydelser
                            </h2>
                            <p>
							Konsultation og sundhedseftersyn (eksl. evt. medicin m.m.) hund/kat: 625 kr.<br>
							<br>
							Konsultation og sundhedseftersyn, gnaver (eksl. medicin m.m.): 500 kr.<br>
							<br>
							Kontrol (efter forudgående konsultation): 250 kr.<br>
							<br>
							Sundhedseftersyn i forbindelse med vaccination (eksl. vaccine), hund/kat: 475 kr.<br>
							<br>
							Sundhedseftersyn i forbindelse med vaccination (eksl. vaccine), kanin: 275 kr.<br>
							<br>
							Pas til kæledyr inkl. udfærdigelse: 225 kr.<br>
							<br>
							Chipmærkning inkl. registrering: 500 kr.<br>
							<br>
							Negleklip hund/kat/kanin hos veterinærsygeplejerske: 200 kr.<br>
							<br>
							Chipmærkning i forbindelse med neutralisering eller anden behandling: 150 kr.<br>
							<br>
							Aflivningshonorar inkl. konsultation, hund/kat ekskl. kremering og medicin : 850 kr.<br>
							<br>
							Aflivningshonorar inkl. konsultation, gnaver/smådyr ekskl. kremering og medicin: 450 kr.<br>
							<br>
							
                            </p>
							
							<h2>
                                Operationer
                            </h2>
                            <p>
							Kastration af kat (inkl. bedøvelse, medicin under operation, materialer, overvågning, operation, øremærke + registrering): fra 900 kr.<br>
							<br>
							Sterilisation af kat ((inkl. bedøvelse, medicin under operation, materialer, krave, overvågning, operation, øremærke + registrering): fra 1200 kr.<br>
							<br>
							Kastration af hund (inkl. bedøvelse, medicin under operation, materialer, krave, overvågning og operation)<br>
							
							<div style="padding-left:1rem;">
									Under 10 kg: ca. 1900 kr.<br>
									<br>
									10-25 kg: ca. 2200 kr.<br>
									<br>
									Over 25 kg: ca.2500 kr.<br>
									<br>
							</div>
							<br>
							Sterilisation af hund (inkl. bedøvelse, medicin under operation, materialer, krave, overvågning og operation) <br>  

							<div style="padding-left:1rem;">
									under 10k g. ca. 4000 kr.<br>
									<br>
									10-25 kg. ca. 4300 kr.<br>
									<br>
									Over 25 kg.: ca 4500 kr.<br>
									<br>
							</div>
							<br>
							Kastration af kanin/marsvin (inkl. bedøvelse, medicin under operation, materialer, overvågning og operation samt CC ved opvågning): ca. 1200 kr.<br>
							<br>
							Sterilisation kanin/marsvin (inkl. bedøvelse, medicin under operation, materialer, krave, overvågning og operation samt CC ved opvågning): ca. 1400kr.<br>

                            </p>
                            </div>

                    </div>
                    <div class="col-md-3 sidebar">
                        <?php tpl('sidebar'); ?>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <?php tpl('footer'); ?>

    <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/da_dk/sdk.js#xfbml=1&version=v3.2&appId=251730689074894&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>